classDiagram
    class game {
        + combat : function
        + menu : menu
        + gameplay : gameplay
        + logic : function
    }
    class gameplay {
        + combat : function
        + player : player
        + maps : list[map]
    }
    class menu {
        + option : function
        + save : function
        + volume : function
        + quit : function
    }
    class entity {
        + move : function
        + combat : function
        + hp : int
        + sprite : list[image]
        + interact : function
        + coordinates : list[x, y]
    }
    class mob {
        + move : function
        + combat : function
        + attack : function
    }
    class object {
        + durability : int
        + form : list
        + use : function
    }
    class map {
        + background : image
        + map : image
        + sectors : list[sector]
        + update : function
    }
    class player {
        + move : function
        + inventory : list[object]
        + held_item : int
        + use_item : function
        + switch_item : function
        + allies : list[ally]
        + open_inventory : function
    }
    class ally {
        + interaction : function
        + move : function
        + attack : function
    }
    class sector {
        + mobs : list[mob]
        + decor : list[decor]
    }
    class decor {
        + coordinates : list[x, y]
        + collision : pygame rect
        + image : image
        + size : int
    }

    gameplay --> player
    gameplay --> map
    game --> gameplay
    game --> menu
    entity <|-- player
    entity <|-- mob    
    entity <|-- ally
    sector --> mob
    sector --> decor
    player --> ally
    map --> sector
